# Generated by Django 4.1.2 on 2022-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Reader'), ('CONTRIBUTOR', 'Editor')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('desc', models.CharField(blank=True, max_length=1255)),
                ('tag', models.CharField(choices=[('B', 'BUG'), ('A', 'AMÉLIORATION'), ('T', 'TÂCHE')], max_length=255)),
                ('priority', models.PositiveSmallIntegerField(choices=[('3', 'FAIBLE'), ('2', 'MOYENNE'), ('1', 'ÉLEVÉE')], default=1)),
                ('status', models.CharField(choices=[('AF', 'A faire'), ('EC', 'En cours'), ('OK', 'Terminé')], max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1255)),
                ('type', models.CharField(choices=[('BE', 'back-end'), ('FE', 'front-end'), ('IO', 'iOS'), ('AD', 'Android')], max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
