# Generated by Django 4.1.2 on 2022-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('3', 'FAIBLE'), ('2', 'MOYENNE'), ('1', 'ÉLEVÉE')], max_length=255),
        ),
    ]
