# Generated by Django 4.1.2 on 2022-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_contributor_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('3 - FAIBLE', 'FAIBLE'), ('2 - MOYENNE', 'MOYENNE'), ('1 - ÉLEVÉE', 'ÉLEVÉE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('A faire', 'AF'), ('En cours', 'EC'), ('Terminé', 'OK')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'B'), ('AMÉLIORATION', 'A'), ('TÂCHE', 'T')], max_length=255),
        ),
    ]
