# Generated by Django 4.1.2 on 2022-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='author_user_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.IntegerField(null=True),
        ),
    ]
