# Generated by Django 4.1.2 on 2022-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_author_user_id_contributor_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
